### ISSUE TITLE
"wp is not defined"

### ISSUE THREAD

**Issue by soderlind** [xwp/wp-customizer-blank-slate#1]
Running the plugin gives me `wp is not defined`:

<img width="736" alt="wp-is-not-defined" src="https://cloud.githubusercontent.com/assets/1649452/18418793/49195e28-784d-11e6-90f3-da8a5e3ef34f.png">

**Comment by westonruter** [comment]
This may be related to an issue I just fixed in Customize Posts, which I can see you using: https://github.com/xwp/wp-customize-posts/pull/258

Otherwise, I didn't test with script concatenation enabled (I have `SCRIPT_DEBUG` turned on).

**Comment by westonruter** [comment]
@soderlind give this a try: https://github.com/xwp/wp-customizer-blank-slate/pull/2

**Comment by soderlind** [comment]
@westonruter,  tested #2 on a new clean site ( local VVV site running WordPress 4.6.1), everything works fine. Thank you. :)

.. on a train with a very slow wifi
