### ISSUE TITLE
Blank slate + beta4, only "Save draft" is available

### ISSUE THREAD

**Issue by soderlind** [xwp/wp-customizer-blank-slate#10]
In 4.9-beta4-42021, I can only save drafts, the option wheel is disabled:

![draft-only](https://user-images.githubusercontent.com/1649452/31987038-ca3bed7c-b96a-11e7-98fd-48cf7f2df8a0.png)

**Comment by westonruter** [comment]
@soderlind I think I know why this is happening and it's because the `publish_settings` section is getting removed. So the immediate fix is to just skip removing the `publish_settings` section.

**Comment by westonruter** [comment]
Or rather, the section isn't getting removed. Rather, it is not getting added to begin with. I think we should be adding the section via JS instead of PHP.

**Comment by westonruter** [comment]
It would probably be best if we made it harder to remove the `publish_settings` section, since the Customizer depends on it.

**Comment by westonruter** [comment]
I've opened https://core.trac.wordpress.org/ticket/42337 to track this for 4.9-RC1

**Comment by westonruter** [comment]
@soderlind I've attached a patch to this core ticket. Would you please test and comment with your findings?

**Comment by soderlind** [comment]
@westonruter, will do :)

**Comment by westonruter** [comment]
Fixed as of https://core.trac.wordpress.org/ticket/42337

See also #11.
