### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by soderlind** [xwp/wp-customizer-blank-slate#3]
@westonruter, when I load my customizer settings using the following, i get `underscore.min.js?ver=1.8.3:5 Uncaught TypeError: Cannot read property 'replace' of undefined`

``` php
add_action( 'wp_loaded', function() {
    add_action( 'customize_register', array( $this, 'customize_plugin' ) );
}, 9 );
```

I get the same error if I trigger the hook in https://github.com/xwp/wp-customizer-blank-slate/blob/master/customizer-blank-slate.php#L62

It looks like the customizer templates aren't loaded at priority 9 (I don't get the JavaScript error if the priority is set to 11 .. but then again, I don't see my settings either).

If I disable the Customizer Blank Slate plugin, my [simple demo plugin](https://gist.github.com/soderlind/2f0c51888277d1fc095646c27080000a) works.

**Comment by westonruter** [comment]
@soderlind please give #4 a try. The reason is because the panel, section, and control types aren't getting registered. So this change ensures they get registered. You could have also handled this yourself by registering the types in your plugin separately.

**Comment by soderlind** [comment]
@westonruter thank you, #4 fixed my issue (and thank you for being patient, I'm still learning, reading code, yours and others)

**Comment by westonruter** [comment]
It's a valid bug, so thanks for pointing it out.
