### ISSUE TITLE
Error when wp-util.js not already enqueued

### ISSUE THREAD

**Issue by NateWr** [xwp/wp-customizer-blank-slate#5]
Thanks for this, saved me a bunch of hours!

I was running into a bug when I tried to integrate it into my plugin. The console reported that `wp.template` was undefined when called in `customize-controls.js:498`, which seemed to be invoked when creating sections.

I stripped everything down and was able to reproduce the problem on TwentyThirteen with just this plugin active (but not TwentySixteen or TwentyFifteen). I eventually tracked it down to a missing `wp-util.js` file.

The following fixes the problem for my plugin:

```
add_action( 'customize_controls_enqueue_scripts', function() {
  wp_enqueue_script( 'wp-util' );
} );
```

But I wondered if this error indicated that there is a missing dependency declaration somewhere in the customizer control scripts in core. Should `wp-util`  be added as a dependency for `customizer-control.js` [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/script-loader.php#L825)?

**Comment by westonruter** [comment]
Actually, you referenced the style registration not the script one. If you scroll to the script registration you see that `wp-util` is indeed added as a dependency. But, this dependency was just added in 4.7-alpha, so the workaround you have should only be needed in 4.6 and below. Props @ocean90 for first finding and fixing: https://core.trac.wordpress.org/ticket/38107

**Comment by NateWr** [comment]
Hah! Alright then, I will have to wait another day for my first props. :)

Thanks for the quick response.

**Comment by westonruter** [comment]
@NateWr you can open a PR that enqueues the `wp-util` plugin for this plugin and get props here 😄

**Comment by NateWr** [comment]
Better late than never I suppose! PR: #6
